4:
	gcc my_tree.cpp -o my_tree -lstdc++ -std=c++17
	./my_tree
	rm my_tree
3:
	gcc my_deleter.cpp -o my_deleter -lstdc++ -std=c++17
	./my_deleter
	rm my_deleter
2:
	gcc my_unique_ptr.cpp -o my_unique_ptr -lstdc++ -std=c++17
	./my_unique_ptr
	rm my_unique_ptr
1:
	gcc my_smart_ptr.cpp -o my_smart_ptr -lstdc++ -std=c++17
	./my_smart_ptr || rm my_smart_ptr

