new03:
	clear
	cat new03.cpp
	g++ new03.cpp -o new03 -lstdc++ -std=c++17
	./new03
	rm new03
new02:
	clear
	cat new02.cpp
	g++ new02.cpp -o new02 -lstdc++ -std=c++17
	./new02
	rm new02
new01:
	clear
	cat new01.cpp
	g++ new01.cpp -o new01 -lstdc++ -std=c++17
	./new01
	rm new01
new00:
	clear
	cat new01.cpp
	g++ new01.cpp -o new01 -lstdc++ -std=c++17 -DUSER_OPERATOR_NEW
	./new01
	rm new01

