3:
	clear
	g++ deikstra.cpp -o deikstra -lstdc++ -std=c++17
	@echo "------------ INPUT -------------------"
	cat graph03.in
	@echo "--------------------------------------"
	cat graph03.in | ./deikstra
	rm deikstra
2:
	clear
	g++ bfs.cpp -o bfs -lstdc++ -std=c++17
	@echo "------------ INPUT -------------------"
	cat graph02.in
	@echo "--------------------------------------"
	cat graph02.in | ./bfs
	@echo "--------------------------------------"
	rm bfs
1:
	clear
	g++ dfs.cpp -o dfs -lstdc++ -std=c++17
	@echo "----------- INPUT --------------------"
	cat graph01.in
	@echo "--------------------------------------"
	cat graph01.in | ./dfs
	@echo "--------------------------------------"
	rm dfs

