4:
	g++ list2.cpp -o list2 -lstdc++ -std=c++17
	./list2
	rm list2
3:
	g++ vec1.cpp -o vec1 -lstdc++ -std=c++17
	./vec1
	rm vec1
2:
	g++ uset1.cpp -o uset1 -lstdc++ -std=c++17
	./uset1
	rm uset1
1:
	g++ list1.cpp -o list1 -lstdc++ -std=c++17
	./list1
	rm list1

