set1:
	g++ set1.cpp -o set1 -lstdc++ -std=c++17
	./set1
	rm set1
new1:
	g++ new1.cpp -o new1 -lstdc++ -std=c++17
	./new1
	rm new1
initi_list:
	g++ init_list.cpp -o init_list -lstdc++ -std=c++17
	./init_list
	rm init_list
vec2:
	g++ vec2.cpp -o vec2 -lstdc++ -std=c++17
	./vec2
	rm vec2
vec1:
	g++ vec1.cpp -o vec1 -lstdc++ -std=c++17
	./vec1
	rm vec1
uset1:
	g++ uset1.cpp -o uset1 -lstdc++ -std=c++17
	./uset1
	rm uset1
list1:
	g++ list1.cpp -o list1 -lstdc++ -std=c++17
	./list1
	rm list1
list2:
	g++ list2.cpp -o list2 -lstdc++ -std=c++17
	./list2
	rm list2
list3:
	g++ list3.cpp -o list3 -lstdc++ -std=c++17 -g
	./list3
	rm list3

