# auto build files
9:
	g++ atomic_user9.cpp -o atomic_user9 -lstdc++ -pthread -std=c++17
	./atomic_user9
	rm atomic_user9
8:
	g++ atomic_wait8.cpp -o atomic_wait8 -lstdc++ -pthread -std=c++20
	./atomic_wait8
	rm atomic_wait8
2:
	g++ atomic2.cpp -o atomic2 -lstdc++ -pthread
	./atomic2
	rm atomic2
7:
	g++ atomic7.cpp -o atomic7 -lstdc++ -pthread
	./atomic7
	rm atomic7
4:
	g++ atomic4.cpp -o atomic4 -lstdc++ -pthread
	./atomic4
	rm atomic4
6:
	g++ atomic6.cpp -o atomic6 -lstdc++ -pthread
	./atomic6
	rm atomic6
3:
	g++ atomic3.cpp -o atomic3 -lstdc++ -pthread
	./atomic3
	rm atomic3
1:
	g++ atomic_spin1.cpp -lstdc++ -o atomic_spin1 -pthread -std=c++17
	./atomic_spin1
	rm atomic_spin1
0:
	g++ atomic0.cpp -lstdc++ -o atomic0 -pthread -std=c++17
	./atomic0
	rm atomic0
clear:
	@echo 'remove all *.o files'
	rm *.o
