10:
	cat rval2.cpp
	g++ rval2.cpp -o rval2 -lstdc++ -std=c++17
	./rval2
	rm rval2
9:
	cat rval1.cpp
	g++ rval1.cpp -o rval1 -lstdc++ -std=c++17
	./rval1
	rm rval
6:
	cat ref6.cpp
	g++ ref6.cpp -o ref6 -lstdc++ -std=c++17
	./ref6
	rm ref6
5:
	cat ref5.cpp
	g++ ref5.cpp -o ref5 -lstdc++ -std=c++17
	./ref5
	rm ref5
4:
	cat ref4.cpp
	g++ ref4.cpp -o ref4 -lstdc++ -std=c++17
	./ref4
	rm ref4
3:
	cat ref3.cpp
	g++ ref3.cpp -o ref3 -lstdc++ -std=c++17
	./ref3
	rm ref3
2:
	cat ref2.cpp
	g++ ref2.cpp -o ref2 -lstdc++ -std=c++17
	./ref2
	rm ref2	
1:
	cat ref1.cpp
	g++ ref1.cpp -o ref1 -lstdc++ -std=c++17
	./ref1
	rm ref1

