collapse_param:
	clear
	cat collapse_param.cpp
	@echo "-------------------------------------------------------"
	g++ collapse_param.cpp -o collapse_param -lstdc++ -std=c++17
	./collapse_param
	rm collapse_param
constexpr-if-sfinae:
	clear
	cat constexpr-if-sfinae.cpp
	@echo "-------------------------------------------------------"
	g++ constexpr-if-sfinae.cpp -o constexpr-if-sfinae -lstdc++ -std=c++17
	./constexpr-if-sfinae
	rm constexpr-if-sfinae
constexpr-if:
	clear
	cat constexpr-if.cpp
	@echo "-------------------------------------------------------"
	g++ constexpr-if.cpp -o constexpr-if -lstdc++ -std=c++17
	./constexpr-if
	rm constexpr-if

