6:
	@clear
	@cat 6noexcept_throw.cpp
	@g++ 6noexcept_throw.cpp -o 6noexcept_throw  -lstdc++ -std=c++17 -Wterminate
	@echo '********************* run ****************'
	@./6noexcept_throw || rm 6noexcept_throw
5:
	@clear
	@cat 5catch_except.cpp
	@g++ 5catch_except.cpp -o 5catch_except -lstdc++ -std=c++17
	@echo '********************* run ****************'
	@./5catch_except
	@rm 5catch_except 
4:	
	@clear
	@cat 4set_user_terminate.cpp
	@g++ 4set_user_terminate.cpp -o 4set_user_terminate -lstdc++ -std=c++17
	@echo '********************* run ****************'
	@./4set_user_terminate || rm 4set_user_terminate 
3:
	@clear
	@cat 3throw.cpp
	@g++ 3throw.cpp -o 3throw -lstdc++ -std=c++17
	@echo '********************* run ****************'
	@./3throw || rm 3throw
2:
	@clear
	@cat 2rollup_stack.cpp
	@g++ 2rollup_stack.cpp -o 2rollup_stack -lstdc++ -std=c++17
	@echo '********************* run ****************'
	@./2rollup_stack
	@rm 2rollup_stack
1:
	@clear
	@cat 1noexcept.cpp
	@g++ 1noexcept.cpp -o 1noexcept -lstdc++ -std=c++17
	@echo '********************* run *****************'
	@./1noexcept
	@rm 1noexcept

