rank:
	gcc rank.cpp -o rank -lstdc++ -std=c++17
	./rank
	rm rank
integral_constant:
	gcc integral_constant.cpp -o integral_constant -lstdc++ -std=c++17
	./integral_constant
	rm integral_constant
decltype:
	gcc decltype.cpp -o decltype -lstdc++ -std=c++17
	./decltype
	rm decltype

