3:
	clear
	cat vec-emplace.cpp
	@echo "------------------------------------------------"
	g++ vec-emplace.cpp -o vec-emplace -lstdc++ -std=c++17
	./vec-emplace
	rm vec-emplace
2:
	clear
	cat remove-quick.cpp
	@echo "------------------------------------------------"
	g++ remove-quick.cpp -o remove-quick -lstdc++ -std=c++17
	./remove-quick
	rm remove-quick
1:
	clear
	cat remove-erase.cpp
	@echo "------------------------------------------------"
	g++ remove-erase.cpp -o remove-erase -lstdc++ -std=c++17
	./remove-erase
	rm remove-erase

