3:
	g++ gtest3.cpp -o gtest3 -lgtest -lgmock -pthread
	./gtest3
	rm gtest3

2:
	g++ gtest2.cpp -o gtest2 -lgtest -lgmock -pthread
	./gtest2
	rm gtest2

1:
	g++ gtest1.cpp -o gtest1 -lgtest -lgmock -pthread
	./gtest1
	rm gtest1



