3:
	g++ deduce_param3.cpp -o deduce_param3 -lstdc++ -std=c++17
	./deduce_param3
	rm deduce_param3
2:
	g++ deduce_param2.cpp -o deduce_param2 -lstdc++ -std=c++17
	./deduce_param2
	rm deduce_param2
1:
	cat deduce_param.cpp
	g++ deduce_param.cpp -o deduce_param -lstdc++ -std=c++17
	./deduce_param
	rm deduce_param
