8:
	cat decltype1.cpp
	g++ decltype1.cpp -o decltype1 -lstdc++ -std=c++17
	./decltype1
	rm decltype1
7:
	cat auto1.cpp
	g++ auto1.cpp -o auto1 -lstdc++ -std=c++17
	./auto1
	rm auto1
6:
	cat deduce6.cpp
	g++ deduce6.cpp -o deduce6 -lstdc++ -std=c++17
	./deduce6
	rm deduce6
5:
	cat deduce5.cpp
	g++ deduce5.cpp -o deduce5 -lstdc++ -std=c++17
	./deduce5
	rm deduce5
4:
	cat deduce4.cpp
	g++ deduce4.cpp -o deduce4 -lstdc++ -std=c++17
	./deduce4
	rm deduce4
3:
	cat deduce3.cpp
	g++ deduce3.cpp -o deduce3 -lstdc++ -std=c++17
	./deduce3
	rm deduce3
2:
	cat deduce2.cpp
	g++ deduce2.cpp -o deduce2 -lstdc++ -std=c++17
	./deduce2
	rm deduce2
1:
	cat deduce1.cpp
	g++ deduce1.cpp -o deduce1 -lstdc++ -std=c++17
	./deduce1
	rm deduce1
0:
	cat factorial.cpp
	g++ factorial.cpp -o factorial -lstdc++ -std=c++17
	./factorial
	rm factorial
